# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('year_released', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=500, null=True)),
                ('genre', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
    ]
